env:
  node: true
  es6: true
  mocha: true
extends:
  - eslint:recommended
  - plugin:prettier/recommended
parserOptions:
  sourceType: module
  ecmaVersion: 2018
rules:
  no-case-declarations: 0
  linebreak-style:
    - error
    - unix
  mocha/no-exclusive-tests: error
plugins:
  - mocha
